In [ ]:
#!pip install numpy==1.25.2

import numpy as np

def euclidean_rhythm(pulses, steps, offset=0):
    """Generates a Euclidean rhythm with an offset.

    Args:
        pulses: The number of pulses (beats).
        steps: The number of steps (time units).
        offset: The number of steps to shift the rhythm.

    Returns:
        A NumPy array representing the rhythm (1 for pulse, 0 for rest).
    """
    pattern = [1] * pulses + [0] * (steps - pulses)  # Initial pattern

    while len(pattern[0]) < steps:
      pattern = [[val] * len(pattern[1]) if val else pattern[1] for val in pattern[0]] + \
                [[val] if val else pattern[0] for val in pattern[1]]
      pattern = pattern[0] if len(pattern) == 1 and isinstance(pattern[0], list) else pattern
      pattern = [pattern] if not isinstance(pattern[0], list) else pattern

    pattern = pattern[0] if isinstance(pattern[0], list) else pattern

    # Apply offset
    offset_pattern = np.roll(pattern, offset)

    return offset_pattern

# Example usage
pulses = 3
steps = 8
offset = 2

rhythm = euclidean_rhythm(pulses, steps, offset)

print(rhythm)  # To see the output, run the code.

V2

In [6]:
import numpy as np

def euclidean_rhythm(pulses, steps, offset=0):
    """Generates a Euclidean rhythm with an offset.

    Args:
        pulses: The number of pulses (beats).
        steps: The number of steps (time units).
        offset: The number of steps to shift the rhythm.

    Returns:
        A NumPy array representing the rhythm (1 for pulse, 0 for rest).
    """
    pattern = [1] * pulses + [0] * (steps - pulses)  # Initial pattern

    # The issue is in this while loop condition. The code tries to get
    # len(pattern[0]) but pattern[0] is an integer, not a list.
    # Change the condition to check the length of the entire pattern list.
    while len(pattern) < steps:
        # Pad the shorter sequence with zeros to make them equal length for concatenation
        a, b = pattern[:pulses], pattern[pulses:]

        # Create a pattern using Bjorklund's algorithm
        if len(a) > len(b):
            pattern = a[:len(b)] + [a_i + b_i for a_i, b_i in zip(a[len(b):], b)] + a[len(b) + len(a[len(b):]):] + b
        else:
            pattern = a + [a_i + b_i for a_i, b_i in zip(a, b[len(a):])] + b[len(a) + len(b[len(a):]):] + b[:len(a)]

    pattern = pattern[:steps]  # truncate pattern to desired steps

    pattern = [1 if val > 0 else 0 for val in pattern]

    # Apply offset
    offset_pattern = np.roll(pattern, offset)

    return offset_pattern

# Example usage
pulses = 3
steps = 8
offset = 0

rhythm = euclidean_rhythm(pulses, steps, offset)

print(rhythm)  # To see the output, run the code.

[1 1 1 0 0 0 0 0]


V3


In [8]:
import numpy as np

def euclidean_rhythm(pulses, steps, offset=0):
    """Generates a Euclidean rhythm with an offset.

    Args:
        pulses: The number of pulses (beats).
        steps: The number of steps (time units).
        offset: The number of steps to shift the rhythm.

    Returns:
        A NumPy array representing the rhythm (1 for pulse, 0 for rest).
    """

    if pulses == 0 or steps == 0:
        return np.zeros(steps, dtype=int)

    pattern = []
    counts = [0] * steps
    remainders = [0] * steps
    divisor = steps - pulses
    remainders[0] = pulses

    for i in range(steps):
        counts[i] = pulses // divisor
        remainders[i] = pulses % divisor
        pulses = divisor
        divisor = remainders[i]
        if divisor == 0:
            break

    level = 0
    build_pattern(pattern, counts, remainders, level, 0, i + 1)

    pattern = pattern[:steps]  # Truncate to desired length

    # Apply offset
    offset_pattern = np.roll(pattern, offset)

    return np.array(offset_pattern)

def build_pattern(pattern, counts, remainders, level, count, max_level):
    """Recursive function to build the Euclidean rhythm pattern."""
    if level == max_level:
        return

    for i in range(counts[level] + (1 if count < remainders[level] else 0)):
        pattern.append(1)

    build_pattern(pattern, counts, remainders, level + 1, count + 1, max_level)

    for i in range(counts[level] + (0 if count < remainders[level] else 1)):
        pattern.append(0)


# Example usage
pulses = 3
steps = 8
offset = 0

rhythm = euclidean_rhythm(pulses, steps, offset)

print(rhythm)

[1 1 1 1 1 1 0 0]


V5


In [15]:
import numpy as np

def euclidean_rhythm(pulses, steps, offset=0):
    """Generates a Euclidean rhythm with an offset.

    Args:
        pulses: The number of pulses (beats).
        steps: The number of steps (time units).
        offset: The number of steps to shift the rhythm.

    Returns:
        A NumPy array representing the rhythm (1 for pulse, 0 for rest).
    """
    if pulses == 0 or steps == 0:
        return np.zeros(steps, dtype=int)

    pattern = [1] * pulses + [0] * (steps - pulses)

    while len(pattern) < steps:
        a, b = pattern[:pulses], pattern[pulses:]

        if len(a) > len(b):
            pattern = a[:len(b)] + [a_i + b_i for a_i, b_i in zip(a[len(b):], b)] + a[len(b) + len(a[len(b):]):] + b
        else:
            pattern = a + [a_i + b_i for a_i, b_i in zip(a, b[len(a):])] + b[len(a) + len(b[len(a):]):] + b[:len(a)]

    pattern = pattern[:steps]
    pattern = [1 if val > 0 else 0 for val in pattern]

    offset_pattern = np.roll(pattern, offset)

    return np.array(offset_pattern)

# Example usage
pulses = 3
steps = 8
offset = 0

rhythm = euclidean_rhythm(pulses, steps, offset)

print(rhythm)

[1 1 1 0 0 0 0 0]
